// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPn2cbLaUQAHfsrdvI1i3-nsv5-R79yhM',
    appId: '1:34248139515:web:3e87a3cc97d19ed60fc65e',
    messagingSenderId: '34248139515',
    projectId: 'todoapps-8fe5f',
    authDomain: 'todoapps-8fe5f.firebaseapp.com',
    storageBucket: 'todoapps-8fe5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPn2cbLaUQAHfsrdvI1i3-nsv5-R79yhM',
    appId: '1:34248139515:android:3e87a3cc97d19ed60fc65e',
    messagingSenderId: '34248139515',
    projectId: 'todoapps-8fe5f',
    storageBucket: 'todoapps-8fe5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPn2cbLaUQAHfsrdvI1i3-nsv5-R79yhM',
    appId: '1:34248139515:ios:3e87a3cc97d19ed60fc65e',
    messagingSenderId: '34248139515',
    projectId: 'todoapps-8fe5f',
    storageBucket: 'todoapps-8fe5f.appspot.com',
    iosBundleId: 'com.example.prak_dbs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPn2cbLaUQAHfsrdvI1i3-nsv5-R79yhM',
    appId: '1:34248139515:macos:3e87a3cc97d19ed60fc65e',
    messagingSenderId: '34248139515',
    projectId: 'todoapps-8fe5f',
    storageBucket: 'todoapps-8fe5f.appspot.com',
    iosBundleId: 'com.example.prak_dbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPn2cbLaUQAHfsrdvI1i3-nsv5-R79yhM',
    appId: '1:34248139515:windows:3e87a3cc97d19ed60fc65e',
    messagingSenderId: '34248139515',
    projectId: 'todoapps-8fe5f',
    authDomain: 'todoapps-8fe5f.firebaseapp.com',
    storageBucket: 'todoapps-8fe5f.appspot.com',
  );
}
